### ISSUE TITLE
Generate team and contributors for homepage automatically from GitHub.

### ISSUE THREAD

**Issue by bmpvieira** [bionode/bionode.github.io#1]
The layout is already generated from a JSON downloaded from GitHub, so it should be just a matter of making query automatically GitHub API.

**Comment by thejmazz** [comment]
I can try to set this up. Looks like `_data.json` is the file in question? How did you get `core` and `members` from the GitHub API? I'm assuming you just saved a GitHub API response? There's private members on the website we'll probably have to auth the GitHub API requests to get those.

I've found
- [orgs/bionode](https://api.github.com/orgs/bionode)
- [orgs/bionode/members](https://api.github.com/orgs/bionode/members)
- [orgs/bionode/public_members](https://api.github.com/orgs/bionode/public_members)

Appending `/orgs/bionode/members?access_token=ACCESS_TOKEN`, returns private and public members, but I still don't see how you are programmatically separating `core` and `members`.

I seem to remember there was a core team from my brief time as an admin ;)

So, maybe you need to be admin to get that info, and its two teams.

In any case, a `curl https://api.github.com/api_url?access_token=$ACCESS_TOKEN > _data.json` as a `package.json` script was what I was thinking for this.

Instead of making an environment variable for the token, committing a token that only has `read:org` permissions should be safe. But then anyone can see private members...which is the case on the website anyways..

**Comment by bmpvieira** [comment]
Thanks for giving a shot at this. I've made both core and contributors public, does it help?

**Comment by thejmazz** [comment]
It does - though maybe you didn't need to? I didn't try `/org/bionode/teams` before lol. (see PS)

Here's my testing with `curl` - I'll commit these into an `npm run gen-members` later..

First, with no auth, on endpoint `orgs/bionode/teams`:
<img width="717" alt="screen shot 2016-02-21 at 1 05 26 pm" src="https://cloud.githubusercontent.com/assets/1270998/13204388/fbaf2064-d89c-11e5-930b-eaf3d538db58.png">

Then with my access token with `read:org` permissions (as an env. var.):
<img width="1001" alt="screen shot 2016-02-21 at 1 08 44 pm" src="https://cloud.githubusercontent.com/assets/1270998/13204406/3a989efe-d89d-11e5-99c8-24865ae080d3.png">

Then copy/pasting the `members_url` and removing the `{/member}` (can obviously automate this easily):
<img width="1194" alt="screen shot 2016-02-21 at 1 20 29 pm" src="https://cloud.githubusercontent.com/assets/1270998/13204432/f0f1cc48-d89d-11e5-9b4b-121a5b83bae7.png">

Will have to remove dupes, but thats easy. 

Would be fun to do this in pure bash lol, but I'll do it up in JS for cross-platform compatibility and so its more readable than a bunch of `curl url | grep login | cut -d':' -f2`s lol. I'll add instructions to the readme how to use the script too. Expect a PR in the next few days..

PS. The teams are still not public - which is fine and should stay that way imo (as shown by unauthenticated API request), but I think you made it so that I, as a member of the org, can see the `core` and `contributors` team (I forget if I could before though).

**Comment by bmpvieira** [comment]
I guess there's really no reason why they shouldn't be public (also since we are trying to display them in the website). It's just a matter of figuring out how GitHub settings. Anyway, great that it's working now. I'll be waiting for the PR :+1:
